# -*- coding: utf-8 -*-
"""Daily.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g4uipvu8ILDQdOO69UnyNhQe2M2JFiVQ
"""

import pandas as pd
import re
import numpy as np

df = pd.read_excel('BigChange.xlsx')

df.head()

df.columns

Case = df.iloc[:,1].values

Death = df.iloc[:,2].values

k=[]
for a in Case:
  b =str(a)
  p= b.split('(')
  p= p[0]
  
  
  k.append(p)

k

m = []

for a in Death:
  b =str(a)
  p= b.split('(')
  p= p[0]
  
  
  m.append(p)

m

arr = [k,m]
lol=pd.DataFrame(arr).T

lol.columns=['Cases','Deaths']

lol.head()

df.drop(["deaths"],axis=1,inplace=True)

df.drop([" cases"],axis=1,inplace=True)

df["Cases"] = lol['Cases']

df["Deaths"] = lol['Deaths']

df.dtypes

df.to_csv("Numberone",index=False)